### ISSUE TITLE
Data sampling problems

### ISSUE THREAD

**Issue by ZChengLong578** [HumamAlwassel/TSP#16]
Hi, @HumamAlwassel
I'm sorry to trouble you again.
The duration of my dataset action was short and many partitions were removed, as shown below:
![1641360174(1)](https://user-images.githubusercontent.com/86870600/148164742-8f935616-b70d-4c8b-a220-026796d338c9.png)
However, after observation, I find that it does not seem to be the problem with the length of the video. Actions with a length of 0-1.5 seconds are in the video, but actions with a length of 1.5-3 seconds are not in the video. Why is this?
![1641360277(1)](https://user-images.githubusercontent.com/86870600/148164866-28203395-03ca-4ef7-8a1e-1c14dc81ee5f.png)

**Comment by ZChengLong578** [comment]
The following code in the train/untrimmed_video_dataset.py function was wrong. It worked fine after I changed maximum () to minimum () :
![1641363783(1)](https://user-images.githubusercontent.com/86870600/148170078-8d128bf0-5ac0-45de-aa74-3c7990f74940.png)
But since the action duration in my data set is short, I change the CLIp_length to 4, is that ok? Will this have a bad effect on the model?

**Comment by HumamAlwassel** [comment]
Hi @ZChengLong578,

Your CSV file is not configured correctly. The 5th column is `video-duration` (i.e. the length of the original videos). However, it seems that you set the values for that column to the length of the segment (i.e. `t-end` - `t-start`). You need to fix the same issue for the column `video-frames` (i.e. see it to the new `video-duration` * `fps`). 

The code you pointed out in `train/untrimmed_video_dataset.py` is correct. If you put a minimum instead of maximum, this will always make all your segments have `t-start` = 0 (which is incorrect). Line 108 of that code is just a sanity check to take care of the exceptional case where `t-start` is a negative number (in which case you should clip it to 0). 

So please keep the code as it is and fix the issue you have in the `video-duration` and `video-frames` columns of your CSV. This should solve your problem. 

As for the `clip_length` = 4, I cannot tell if it will have a bad effect on your dataset or not. My guess is that it should be fine, and the model will adapt if you have enough data. The reason we use `clip_lenght` = 8 in the original TSP code is to mimic the same training setup of the R(2+1)D model in the original paper.

Hope this helps!
